/*
Deployment script for EDWAdmin

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar MetadataLogMountPoint "C:\SQLData"
:setvar MetadataDataMountPoint "C:\SQLData"
:setvar DatabaseName "EDWAdmin"
:setvar DefaultFilePrefix "EDWAdmin"
:setvar DefaultDataPath ""
:setvar DefaultLogPath ""

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [master];


GO

IF (DB_ID(N'$(DatabaseName)') IS NOT NULL) 
BEGIN
    ALTER DATABASE [$(DatabaseName)]
    SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [$(DatabaseName)];
END

GO
PRINT N'Creating $(DatabaseName)...'
GO
CREATE DATABASE [$(DatabaseName)]
    ON 
    PRIMARY(NAME = [HCEDWAdminPrimary], FILENAME = '$(MetadataDataMountPoint)\HC$(DatabaseName)Primary.mdf'), 
    FILEGROUP [HCEDWAdminIndex1](NAME = [HCEDWAdminIndex1File1], FILENAME = '$(MetadataDataMountPoint)\HC$(DatabaseName)Index1File1.ndf'), 
    FILEGROUP [HCEDWAdminData1](NAME = [HCEDWAdminData1File1], FILENAME = '$(MetadataDataMountPoint)\HC$(DatabaseName)Data1File1.ndf')
    LOG ON (NAME = [HCEDWAdminLogFile1], FILENAME = '$(MetadataLogMountPoint)\HC$(DatabaseName)LogFile1.ldf') COLLATE SQL_Latin1_General_CP1_CI_AS
GO
USE [$(DatabaseName)];


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS ON,
                ANSI_PADDING ON,
                ANSI_WARNINGS ON,
                ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                NUMERIC_ROUNDABORT OFF,
                QUOTED_IDENTIFIER ON,
                ANSI_NULL_DEFAULT ON,
                CURSOR_DEFAULT GLOBAL,
                RECOVERY FULL,
                CURSOR_CLOSE_ON_COMMIT OFF,
                AUTO_CREATE_STATISTICS ON,
                AUTO_SHRINK OFF,
                AUTO_UPDATE_STATISTICS ON,
                RECURSIVE_TRIGGERS OFF 
            WITH ROLLBACK IMMEDIATE;
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_CLOSE OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ALLOW_SNAPSHOT_ISOLATION OFF;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET READ_COMMITTED_SNAPSHOT ON 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET AUTO_UPDATE_STATISTICS_ASYNC OFF,
                PAGE_VERIFY CHECKSUM,
                DATE_CORRELATION_OPTIMIZATION OFF,
                ENABLE_BROKER,
                PARAMETERIZATION SIMPLE,
                SUPPLEMENTAL_LOGGING OFF 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET TRUSTWORTHY OFF,
        DB_CHAINING OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
IF IS_SRVROLEMEMBER(N'sysadmin') = 1
    BEGIN
        IF EXISTS (SELECT 1
                   FROM   [master].[dbo].[sysdatabases]
                   WHERE  [name] = N'$(DatabaseName)')
            BEGIN
                EXECUTE sp_executesql N'ALTER DATABASE [$(DatabaseName)]
    SET HONOR_BROKER_PRIORITY OFF 
    WITH ROLLBACK IMMEDIATE';
            END
    END
ELSE
    BEGIN
        PRINT N'The database settings cannot be modified. You must be a SysAdmin to apply these settings.';
    END


GO
ALTER DATABASE [$(DatabaseName)]
    SET TARGET_RECOVERY_TIME = 0 SECONDS 
    WITH ROLLBACK IMMEDIATE;


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET FILESTREAM(NON_TRANSACTED_ACCESS = OFF),
                CONTAINMENT = NONE 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF fulltextserviceproperty(N'IsFulltextInstalled') = 1
    EXECUTE sp_fulltext_database 'enable';


GO
CREATE SCHEMA [CatalystAdmin]
    AUTHORIZATION [dbo];


GO
CREATE TABLE [CatalystAdmin].[IdentityBASE](
	[IdentityID] [int] IDENTITY(1,1) NOT NULL,
	[IdentityNM] [varchar](255) NOT NULL,
 CONSTRAINT [pkIdentityBASE] PRIMARY KEY CLUSTERED 
(
	[IdentityID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [HCEDWAdminData1]
) ON [HCEDWAdminData1]

GO

CREATE TABLE [CatalystAdmin].[IdentityRoleBASE](
	[IdentityRoleID] [int] IDENTITY(1,1) NOT NULL,
	[IdentityID] [int] NOT NULL,
	[RoleID] [int] NOT NULL,
 CONSTRAINT [pkIdentityRoleBASE] PRIMARY KEY CLUSTERED 
(
	[IdentityRoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [HCEDWAdminData1]
) ON [HCEDWAdminData1]

GO

CREATE TABLE [CatalystAdmin].[RoleBASE](
	[RoleID] [int] IDENTITY(1,1) NOT NULL,
	[RoleNM] [varchar](255) NOT NULL,
	[RoleDSC] [varchar](4000) NULL,
 CONSTRAINT [pkRoleBASE] PRIMARY KEY CLUSTERED 
(
	[RoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [HCEDWAdminData1]
) ON [HCEDWAdminData1]

GO
ALTER TABLE [CatalystAdmin].[IdentityRoleBASE]  WITH CHECK ADD  CONSTRAINT [fkIdentityRoleBASEIdentityBASE] FOREIGN KEY([IdentityID])
REFERENCES [CatalystAdmin].[IdentityBASE] ([IdentityID])
GO
ALTER TABLE [CatalystAdmin].[IdentityRoleBASE] CHECK CONSTRAINT [fkIdentityRoleBASEIdentityBASE]
GO
ALTER TABLE [CatalystAdmin].[IdentityRoleBASE]  WITH CHECK ADD  CONSTRAINT [fkIdentityRoleBASERoleBASE] FOREIGN KEY([RoleID])
REFERENCES [CatalystAdmin].[RoleBASE] ([RoleID])
GO
ALTER TABLE [CatalystAdmin].[IdentityRoleBASE] CHECK CONSTRAINT [fkIdentityRoleBASERoleBASE]
GO
